const { test, expect } = require("@playwright/test")

test("verify the keyboardActions", async ({ page }) => {
     await page.goto("https://gotranscript.com/text-compare")
     //await page.keyboard.down('PageDown')
     await page.locator('textarea[name="text1"]').fill("I am learning Javascript")
     await page.keyboard.press('Control+A')
     await page.keyboard.press('Control+C')
     //await page.locator('textarea[name="text2"]').click()
     await page.keyboard.down('Tab')
     await page.keyboard.press('Control+V')
     await page.keyboard.press('Shift+Digit2')
     await page.keyboard.press('Shift+Digit5')
     await page.waitForTimeout(3000)
})